### ISSUE TITLE
Link to synrtf in the module's doc

### ISSUE THREAD

**Issue by neilb** [rjbs/RTF-VimColor#1]
I would have submitted a pull request, but I can never remember whether it should be:

```
L<synrtf>
```

or

```
L<synrtf|https://metacpan.org/pod/distribution/RTF-VimColor/bin/synrtf>
```

The former being more portable, but the latter perhaps actually working across all pod processors.

**Comment by rjbs** [comment]
thanks, did the former in 8f312d1
